sonar.projectKey=alice-crm-etudiants
sonar.projectName=Alice CRM Étudiants
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Sources applicatives PHP/Symfony
sonar.sources=src,config,templates,public
sonar.tests=tests
sonar.php.file.suffixes=.php

# Ne pas analyser les dépendances, caches, cartes et ressources vendorizées.
sonar.exclusions=vendor/**,var/**,public/bundles/**,public/assets/**,public/fontawesome/**,public/uploads/**,**/*.min.js,**/*.map
sonar.test.exclusions=tests/**

# Activé automatiquement si PHPUnit produit ce fichier.
sonar.php.coverage.reportPaths=var/coverage/clover.xml
